# Generated by Django 6.0.5 on 2026-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
