# Generated by Django 6.0.5 on 2026-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
