"""
Django settings for walia_blog project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

try:
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=BASE_DIR / '.env')
    load_dotenv(dotenv_path=BASE_DIR / '.env.local', override=True)
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-build-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

def _append_unique(items, value):
    value = (value or '').strip()
    if value and value not in items:
        items.append(value)


def _production_host_variants(hostname):
    """Apex and www variants for a custom production domain."""
    hostname = (hostname or '').strip().lower()
    if not hostname or hostname.startswith('.'):
        return
    yield hostname
    if hostname.startswith('www.'):
        apex = hostname[4:]
        if apex:
            yield apex
    else:
        yield f'www.{hostname}'


def _register_host(hostname, allowed_hosts, csrf_origins):
    hostname = (hostname or '').strip()
    if not hostname:
        return
    _append_unique(allowed_hosts, hostname)
    _append_unique(csrf_origins, f'https://{hostname}')


ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,.vercel.app,.onrender.com',
    ).split(',')
    if host.strip()
]

# Auto-register Render hostname if present
render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    _register_host(render_host, ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS)


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Vercel sets deployment URLs automatically; custom domains are not covered by .vercel.app.
for env_name in ('VERCEL_URL', 'VERCEL_BRANCH_URL'):
    _register_host(os.getenv(env_name), ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS)

production_host = os.getenv('VERCEL_PROJECT_PRODUCTION_URL')
for host in _production_host_variants(production_host):
    _register_host(host, ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'blogs.apps.BlogsConfig',
    'accounts',
]

for app in ('crispy_forms', 'crispy_bootstrap4'):
    try:
        __import__(app)
        INSTALLED_APPS.append(app)
    except ImportError:
        pass

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'walia_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blogs.context_processors.get_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'walia_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


try:
    import psycopg2  # noqa: F401
    has_postgres_driver = True
except ImportError:
    try:
        import psycopg  # noqa: F401
        has_postgres_driver = True
    except ImportError:
        has_postgres_driver = False

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL and dj_database_url and has_postgres_driver:
    # Respect sslmode in the URL; Neon/Vercel Postgres needs SSL in production.
    ssl_disabled = 'sslmode=disable' in DATABASE_URL.lower()
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG and not ssl_disabled,
        ),
    }
elif os.getenv('DB_NAME') and has_postgres_driver:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'walia_blog' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
WHITENOISE_AUTOREFRESH = DEBUG

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Vercel terminates TLS at the edge; avoid redirect loops behind the proxy.
    SECURE_SSL_REDIRECT = (
        os.getenv('SECURE_SSL_REDIRECT', 'False' if os.getenv('VERCEL') else 'True').lower()
        == 'true'
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Cloudinary configuration

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
